name: SSH Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        REMOTE_HOST: github.com
        REMOTE_USER: git
        REMOTE_PORT: 22
        TARGET: git@github.com:starlf/starlf.github.io.git
        ARGS: -rltgoDzvO
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: -avz --delete --exclude='.git/' /path/to/actual/local/directory /path/to/actual/remote/directory