name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 触发构建的源分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true # 如果有子模块的话

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # 根据需要调整版本
        cache: 'pnpm' # 使用 pnpm 缓存

    - name: Debug pnpm-lock.yaml
      run: |
        if [ -f pnpm-lock.yaml ]; then
          echo "pnpm-lock.yaml exists:"
          cat pnpm-lock.yaml
        else
          echo "pnpm-lock.yaml does not exist!"
        fi

    - name: Install dependencies and build site
      run: |
        pnpm install # 使用 pnpm 安装依赖
        pnpm run build # 构建站点

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # 构建后的站点输出目录，根据实际情况调整
        commit_message: ${{ github.event.head_commit.message }} # 可选：使用最近一次提交的消息作为此次部署的提交消息